# Generated by Django 2.1 on 2018-08-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='links',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
