# Generated by Django 2.1 on 2018-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_show_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='links',
            field=models.CharField(max_length=600),
        ),
    ]
