# Generated by Django 2.1 on 2018-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0004_show_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ratingdetails',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
